/**
 * Phase 7 / 7.2 — WCAG 2.1 AA Browser Accessibility Audit
 *
 * Crawls the listed routes with Playwright + axe-core (wcag2a / wcag2aa /
 * wcag21a / wcag21aa), grades each page, and writes a machine-readable report
 * to `reports/accessibility-audit-report.json`.
 *
 * Auth: reuses the e2e storage states cached in `.auth/<role>.json`
 * (generated by `e2e/global-setup.ts` against seeded credentials). If a
 * storage state is missing it falls back to a UI login using the seeded
 * test accounts.
 *
 * Usage:
 *   tsx scripts/a11y/accessibility-audit.ts [--base-url http://localhost:3000]
 *       [--report reports/accessibility-audit-report.json]
 *       [--roles staff,admin] [--gate serious]
 *
 * Exit code 0 = gate passed, 1 = gate failed.
 */
import * as fs from "fs";
import * as path from "path";
import { chromium, type Browser } from "@playwright/test";
import AxeBuilder, { type Result } from "@axe-core/playwright";

interface Args {
  baseUrl: string;
  reportPath: string;
  authDir: string;
  roles: string[];
  gate: "critical" | "serious";
}

interface PageAudit {
  url: string;
  role: string | null;
  pass: boolean;
  violations: Array<{
    id: string;
    impact: string;
    help: string;
    nodes: number;
    detail?: Array<{ target: string; html: string; summary: string }>;
  }>;
  counts: Record<string, number>;
  pagesFullyAnalyzed?: boolean;
}

interface AuditReport {
  generatedAt: string;
  axeVersion: string;
  baseUrl: string;
  ruleset: string[];
  gate: string;
  pages: PageAudit[];
  summary: {
    totalPages: number;
    passedPages: number;
    failedPages: number;
    totalViolations: number;
    byImpact: Record<string, number>;
    byRule: Record<string, number>;
  };
  pass: boolean;
}

const DEFAULTS: Args = {
  baseUrl: "http://localhost:3000",
  reportPath: "reports/accessibility-audit-report.json",
  authDir: ".auth",
  roles: ["staff", "admin"],
  gate: "serious",
};

const RULESET = ["wcag2a", "wcag2aa", "wcag21a", "wcag21aa"];

const ROUTES_BY_ROLE: Record<string, { role: string | null; paths: string[] }[]> = {
  public: [
    { role: null, paths: ["/auth/login", "/auth/signup"] },
  ],
  staff: [
    { role: "staff", paths: ["/", "/attendance", "/tasks", "/circulars", "/help-desk"] },
  ],
  admin: [
    { role: "admin", paths: ["/staff", "/admin/departments", "/admin/institutions", "/admin/audit-logs"] },
  ],
};

function parseArgs(argv: string[]): Args {
  const args: Args = { ...DEFAULTS };
  for (let i = 0; i < argv.length; i++) {
    const flag = argv[i];
    const value = argv[i + 1];
    if (flag === "--base-url" && value) {
      args.baseUrl = value.replace(/\/+$/, "");
      i++;
    } else if (flag === "--report" && value) {
      args.reportPath = value;
      i++;
    } else if (flag === "--auth-dir" && value) {
      args.authDir = value;
      i++;
    } else if (flag === "--roles" && value) {
      args.roles = value.split(",").map((r) => r.trim()).filter(Boolean);
      i++;
    } else if (flag === "--gate" && (value === "critical" || value === "serious")) {
      args.gate = value;
      i++;
    }
  }
  return args;
}

function impactRank(impact?: string): number {
  switch (impact) {
    case "critical":
      return 3;
    case "serious":
      return 2;
    case "moderate":
      return 1;
    default:
      return 0;
  }
}

function gatePasses(violations: Result[], gate: "critical" | "serious"): boolean {
  const threshold = gate === "serious" ? 2 : 3;
  return violations.every((v) => impactRank(v.impact) < threshold);
}

async function ensureSession(browser: Browser, role: string | null, baseUrl: string, authDir: string) {
  const contextOptions: any = { baseURL: baseUrl };
  const statePath = role ? path.join(authDir, `${role}.json`) : null;
  if (statePath && fs.existsSync(statePath)) {
    contextOptions.storageState = statePath;
    return browser.newContext(contextOptions);
  }
  const context = await browser.newContext(contextOptions);
  if (role) {
    const page = await context.newPage();
    const email = ROLE_EMAILS[role] || "test-staff@thaibahive.local";
    await page.goto("/auth/login");
    await page.waitForSelector("form[data-hydrated='true']", { timeout: 45000 });
    await page.waitForSelector("#email", { timeout: 20000 });
    await page.fill("#email", email);
    await page.fill("#password", "Password123");
    await Promise.all([
      page.waitForURL((url) => url.pathname !== "/auth/login", { timeout: 15000 }).catch(() => {}),
      page.click("button[type='submit']"),
    ]);
    await page.waitForLoadState("domcontentloaded").catch(() => {});
    await page.context().storageState({ path: statePath || path.join(authDir, `${role}.json`) });
    await page.close();
  }
  return context;
}

const ROLE_EMAILS: Record<string, string> = {
  super_admin: "test-superadmin@thaibahive.local",
  admin: "test-admin@thaibahive.local",
  principal: "test-principal@thaibahive.local",
  hod: "test-hod@thaibahive.local",
  staff: "test-staff@thaibahive.local",
};

async function auditPage(
  browser: Browser,
  pathname: string,
  role: string | null,
  args: Args
): Promise<PageAudit> {
  const context = await ensureSession(browser, role, args.baseUrl, args.authDir);
  try {
    const page = await context.newPage();
    await page.goto(pathname, { waitUntil: "domcontentloaded", timeout: 45000 });
    // Allow fonts, images and client-side tables to settle, but do NOT wait for
    // network idle: realtime pages keep SSE/WebSocket connections open.
    await page.waitForTimeout(1200);
    const results = await new AxeBuilder({ page }).withTags(RULESET).analyze();

    const violations: PageAudit["violations"] = results.violations.map((v) => ({
      id: v.id,
      impact: v.impact || "minor",
      help: v.help,
      nodes: v.nodes.length,
      detail: v.nodes.slice(0, 5).map((n) => ({
        target: n.target.join(" ").slice(0, 200),
        html: n.html.slice(0, 300),
        summary: (n.failureSummary || "").replace(/\s+/g, " ").trim().slice(0, 400),
      })),
    }));
    const counts: Record<string, number> = { critical: 0, serious: 0, moderate: 0, minor: 0 };
    for (const v of violations) counts[v.impact] = (counts[v.impact] || 0) + 1;

    const pass = gatePasses(results.violations, args.gate);
    return {
      url: `${args.baseUrl}${pathname}`,
      role,
      pass,
      violations,
      counts,
      pagesFullyAnalyzed: results.passes.length > 0,
    };
  } finally {
    await context.close();
  }
}

async function main(): Promise<void> {
  const args = parseArgs(process.argv.slice(2));
  fs.mkdirSync(path.dirname(args.reportPath), { recursive: true });

  const browser = await chromium.launch();
  try {
    const pages: PageAudit[] = [];

    for (const entry of ROUTES_BY_ROLE.public) {
      for (const p of entry.paths) {
        pages.push(await auditPage(browser, p, null, args));
      }
    }
    if (args.roles.includes("staff")) {
      for (const entry of ROUTES_BY_ROLE.staff) {
        for (const p of entry.paths) {
          pages.push(await auditPage(browser, p, entry.role, args));
        }
      }
    }
    if (args.roles.includes("admin")) {
      for (const entry of ROUTES_BY_ROLE.admin) {
        for (const p of entry.paths) {
          pages.push(await auditPage(browser, p, entry.role, args));
        }
      }
    }

    const passedPages = pages.filter((p) => p.pass).length;
    let totalViolations = 0;
    const byImpact: Record<string, number> = {};
    const byRule: Record<string, number> = {};
    for (const p of pages) {
      totalViolations += p.violations.length;
      for (const v of p.violations) {
        byImpact[v.impact] = (byImpact[v.impact] || 0) + 1;
        byRule[v.id] = (byRule[v.id] || 0) + 1;
      }
    }

    const report: AuditReport = {
      generatedAt: new Date().toISOString(),
      axeVersion: "4.x",
      baseUrl: args.baseUrl,
      ruleset: RULESET,
      gate: args.gate,
      pages,
      summary: {
        totalPages: pages.length,
        passedPages,
        failedPages: pages.length - passedPages,
        totalViolations: totalViolations,
        byImpact,
        byRule,
      },
      pass: pages.length > 0 && passedPages === pages.length,
    };

    fs.writeFileSync(args.reportPath, JSON.stringify(report, null, 2), "utf8");
    console.log(`Accessibility audit complete -> ${args.reportPath}`);
    console.log(`Pages: ${pages.length} | Passed: ${passedPages} | Failed: ${pages.length - passedPages}`);
    console.log(`Total violations: ${totalViolations} (by impact: ${JSON.stringify(byImpact)})`);
    for (const p of pages.filter((x) => !x.pass)) {
      console.log(`  FAIL: ${p.url} ${JSON.stringify(p.counts)} ${p.violations.map((v) => v.id).join(",")}`);
    }

    if (!report.pass) {
      console.error("Accessibility gate FAILED: pages with critical/serious violations above threshold detected.");
      process.exit(1);
    }
  } finally {
    await browser.close();
  }
}

main().catch((err) => {
  console.error("Accessibility audit errored:", err);
  process.exit(1);
});