export type StaffRole =
  | "super_admin"
  | "admin"
  | "principal"
  | "hod"
  | "staff"
  | "accounts"
  | "purchase"
  | "regional_admin"
  | "regional_auditor"
  | "coordinator"
  | "institutional_head"
  | "academic_coordinator"
  | "exam_coordinator"
  | "teacher"
  | "inspector"
  | "system";

type Permission = string;

const basePermissions = {
  system: [
    "system:update",
    "system:manage",
    "system:telemetry",
    "system:admin",
    "system:sync",
    "system:cache:sync",
    "system:dr",
    "system:read",
    "system:cron",
    "cache:manage",
    "media:reconcile",
    "media:manage",
    "dr:manage",
    "sync:manage",
    "sync:device",
    "cron:run",
    "telemetry:ingest",
    "mobile:sync",
    "cleanup:execute",
  ],
  coordinator: [
    "campus.approve", "campus:approve", "teacher.assign", "teacher:assign", "academic.grade.create", "academic:grade:create",
    "regional:view", "regional:manage", "warehouse:export", "alerts:push_configure",
    "analytics:predict", "analytics:manage", "analytics:read", "analytics:timeseries", "reports:read", "reports:review", "staff:read",
    "autonomy:view", "autonomy:manage", "compliance:audit", "compliance:forensics", "compliance:read", "compliance:manage", "compliance:export",
    "circulars:read", "circulars:create", "circulars:manage",
    "affiliations:manage", "academic_years:manage", "classes:read", "classes:create", "classes:update",
    "timetables:read", "timetables:manage", "enquiries:read", "enquiries:manage",
    "operations:read", "observability:read",
  ],
  institutional_head: [
    "student.create", "students:create", "students:read", "students:update", "students:delete", "students:write",
    "marks.approve", "marks:approve", "exam:approve_marks", "exam:publish_results", "exam:read",
    "staff:read", "staff:create", "staff:update",
    "attendance:read", "attendance:manage", "student_attendance:read", "student_attendance:manage",
    "tasks:read", "tasks:create", "tasks:assign",
    "leaves:read", "leaves:approve", "leaves:delete", "leave:manage", "approvals:approve",
    "reports:read", "reports:review", "reports:create",
    "announcements:read", "announcements:create", "events:read", "events:create", "polls:read", "circulars:read", "circulars:create",
    "bookings:read", "bookings:create", "bookings:manage", "helpdesk:read", "helpdesk:create", "helpdesk:manage",
    "assets:read", "assets:create", "assets:update",
    "finance:read", "finance:create", "finance:update", "finance:export", "finance:approve",
    "finance:fees:view", "finance:fees:manage", "finance:fees:collect", "finance:reconciliation:manage", "finance:scholarships:view", "finance:scholarships:approve",
    "accounts:view", "recognition:create", "canteen:create", "canteen:read", "canteen:manage", "canteen:redeem",
    "checklists:update", "notifications:update", "visitors:create", "visitors:update", "visitors:read", "visitors:manage", "visitor:read", "visitor:issue", "visitor:verify",
    "vehicles:read", "vehicles:manage", "fleet:read", "fleet:manage", "fleet:book", "grievances:read", "chat:read", "chat:manage",
    "availability:write", "media:read", "media:create", "media:share", "nfc:admin", "nfc:assign", "webauthn:manage", "marketplace:install", "marketplace:uninstall",
    "classes:read", "classes:create", "classes:update", "classes:delete", "academic_years:manage", "timetables:read", "timetables:manage", "enquiries:read", "enquiries:manage", "affiliations:manage",
    "documents:read", "documents:generate", "documents:templates:manage", "documents:telemetry:view", "exports:read", "exports:create", "mobile:sync",
    "biometric:enroll", "biometric:admin", "performance:read", "performance:manage", "performance:evaluate", "performance:self", "analytics:predict", "analytics:manage", "analytics:read", "analytics:timeseries",
    "curriculum:advising:chat", "curriculum:audit:execute", "curriculum:catalog:manage", "curriculum:plans:approve", "curriculum:plans:edit", "curriculum:plans:view", "curriculum:retention:intervene", "curriculum:retention:view", "curriculum:transfer:articulate",
    "km:advising:audit", "km:analytics:view", "km:knowledge:search", "reviews:read", "reviews:create", "reviews:update",
  ],
  academic_coordinator: [
    "academic.grade.create", "academic:grade:create", "teacher.assign", "teacher:assign",
    "academic_years:manage", "classes:read", "classes:create", "classes:update",
    "timetables:read", "timetables:manage",
    "curriculum:catalog:manage", "curriculum:plans:view", "curriculum:plans:edit", "curriculum:plans:approve",
    "students:read", "student_attendance:read", "staff:read",
    "documents:read", "documents:generate", "exports:read", "exports:create",
  ],
  exam_coordinator: [
    "exam:create", "exam:read", "exam:publish_results", "exam:enter_marks", "exam:approve_marks",
    "marks.approve", "marks:approve",
    "classes:read", "students:read", "academic_years:manage",
    "documents:read", "documents:generate", "exports:read", "exports:create",
  ],
  teacher: [
    "marks.enter", "marks:enter", "exam:enter_marks", "exam:read",
    "student_attendance:read", "student_attendance:manage", "attendance:read",
    "timetables:read", "classes:read", "students:read",
    "tasks:read", "leaves:read", "leaves:delete", "reports:create", "reports:read",
    "announcements:read", "events:read", "polls:read", "circulars:read",
    "grievances:create", "canteen:read", "canteen:create", "bookings:read", "bookings:create",
    "helpdesk:read", "helpdesk:create", "chat:read", "chat:manage", "media:read", "media:create", "media:share",
    "profile:read", "profile:write",
  ],
  inspector: [
    "reports:read", "reports:review", "staff:read", "attendance:read", "student_attendance:read",
    "exam:read", "classes:read", "students:read", "compliance:read", "compliance:audit",
    "regional:view", "autonomy:view", "operations:read", "observability:read",
  ],
};

const rolePermissions: Record<StaffRole, Permission[]> = {
  super_admin: ["*"],
  system: basePermissions.system,
  coordinator: basePermissions.coordinator,
  institutional_head: basePermissions.institutional_head,
  academic_coordinator: basePermissions.academic_coordinator,
  exam_coordinator: basePermissions.exam_coordinator,
  teacher: basePermissions.teacher,
  inspector: basePermissions.inspector,

  regional_admin: [
    "campus.approve", "campus:approve", "teacher.assign", "teacher:assign", "academic.grade.create", "academic:grade:create",
    "regional:view", "regional:manage", "warehouse:export", "alerts:push_configure",
    "analytics:predict", "analytics:manage", "analytics:read", "analytics:timeseries", "reports:read", "reports:review", "staff:read",
    "autonomy:view", "autonomy:manage", "compliance:audit", "compliance:forensics", "compliance:read", "compliance:manage", "compliance:export", "financial:forecast",
    "copilot:view", "copilot:interact", "agent:manage", "agents:manage",
    "realtime:stream", "triggers:manage", "predictive:retention", "simulation:budget",
    "federated:policies", "federated:audit", "federated:read", "federated:manage", "federated:train", "federation:manage",
    "resilience:manage", "voice:copilot", "executive:analytics",
    "workspaces:read", "workspaces:write", "system:manage", "system:admin",
    "system:energy:manage", "system:fleet:manage", "system:biometrics:verify", "system:operations:manage", "system:sustainability:view", "system:operations:view",
    "system:security:view", "system:security:manage", "system:threat-intel:view", "system:threat-intel:manage", "system:threat-intel:federate",
    "operations:read", "operations:write", "observability:read", "observability:write",
    "documents:read", "documents:generate", "documents:templates:manage", "documents:telemetry:view", "exports:read", "exports:create", "mobile:sync",
    "facility:equipment:view", "facility:equipment:manage", "facility:telemetry:ingest", "facility:alerts:view", "facility:alerts:triage", "facility:workorders:view", "facility:workorders:create", "facility:workorders:assign", "facility:workorders:execute", "facility:inventory:manage", "facility:contractors:manage", "facility:energy:loadshed",
    "twin:facilities:read", "twin:facilities:write", "twin:assets:manage", "twin:iot:ingest", "twin:optimization:manage", "twin:emergency:trigger",
    "eco:assets:manage", "eco:carbon:manage", "eco:carbon:view", "eco:ev:manage", "eco:microgrid:control", "eco:reports:generate", "eco:telemetry:ingest",
    "vision:alerts:view", "vision:alerts:manage", "vision:alpr:manage", "vision:cameras:manage", "vision:guards:dispatch", "vision:incidents:manage", "vision:lockdown:execute", "vision:privacy:audit",
    "neuro:clusters:view", "neuro:clusters:manage", "neuro:gpus:view", "neuro:gpus:manage", "neuro:jobs:view", "neuro:jobs:submit", "neuro:jobs:manage", "neuro:metrics:view", "neuro:nodes:view", "neuro:nodes:manage", "neuro:provenance:view", "neuro:provenance:manage", "neuro:scheduler:view", "neuro:scheduler:manage", "neuro:stream:view", "neuro:arbitrage:view", "neuro:arbitrage:manage", "neuro:billing:view", "neuro:billing:manage",
    "alumni:chapters:view", "alumni:chapters:manage", "alumni:directory:view", "alumni:donations:view", "alumni:donations:manage", "alumni:donations:collect", "alumni:events:view", "alumni:events:manage", "alumni:events:rsvp", "alumni:events:checkin", "alumni:jobs:view", "alumni:jobs:post", "alumni:jobs:apply", "alumni:jobs:manage", "alumni:mentorship:view", "alumni:mentorship:manage", "alumni:profile:view", "alumni:profile:manage",
    "supply:contracts:manage", "supply:invoices:match", "supply:orders:approve", "supply:orders:manage", "supply:orders:view", "supply:receipts:record", "supply:requisitions:create", "supply:requisitions:view", "supply:stream:view", "supply:vendors:manage", "supply:vendors:view",
    "finance:read", "finance:create", "finance:update", "finance:delete", "finance:export", "finance:approve", "finance:fees:view", "finance:fees:manage", "finance:fees:collect", "finance:reconciliation:manage", "finance:scholarships:view", "finance:scholarships:approve", "accounts:view", "accounts:create", "accounts:manage",
    "finance:tax:view", "finance:tax:manage", "finance:tax:override", "finance:purchases:create", "finance:purchases:approve:tier1", "finance:purchases:approve:tier2", "finance:purchases:approve:final", "finance:payroll:view", "finance:payroll:manage", "finance:payroll:export", "finance:reconciliation:execute", "finance:reconciliation:view",
    "approvals:approve",
    "agent:workflows:view", "agent:workflows:manage", "agent:memory:view", "agent:audit:view", "agent:guardrails:manage", "agent:telemetry:view",
  ],
  regional_auditor: [
    "regional:view", "warehouse:export", "reports:read", "reports:review", "staff:read",
    "autonomy:view", "compliance:audit", "compliance:read", "compliance:export",
    "copilot:view", "copilot:interact", "analytics:timeseries", "analytics:read",
    "realtime:stream", "predictive:retention",
    "federated:policies", "federated:audit", "federated:read", "voice:copilot",
    "operations:read", "observability:read", "system:security:view", "system:threat-intel:view",
    "documents:read", "exports:read",
    "facility:equipment:view", "facility:alerts:view", "facility:workorders:view",
    "twin:facilities:read", "eco:carbon:view", "eco:reports:generate",
    "vision:alerts:view", "vision:privacy:audit",
    "neuro:clusters:view", "neuro:metrics:view", "neuro:provenance:view", "neuro:billing:view",
    "alumni:directory:view", "alumni:donations:view", "alumni:events:view",
    "supply:orders:view", "supply:vendors:view", "supply:requisitions:view",
    "finance:read", "finance:fees:view", "finance:scholarships:view", "accounts:view",
    "finance:tax:view", "finance:payroll:view", "finance:reconciliation:view",
    "agent:workflows:view", "agent:audit:view", "agent:telemetry:view",
  ],
  admin: [
    "student.create", "students:create", "students:read", "students:update", "students:delete", "students:write",
    "marks.enter", "marks:enter", "marks.approve", "marks:approve", "teacher.assign", "teacher:assign", "campus.approve", "campus:approve", "academic.grade.create", "academic:grade:create",
    "staff:read", "staff:create", "staff:update", "staff:delete",
    "attendance:read", "attendance:manage",
    "tasks:read", "tasks:create", "tasks:assign",
    "leaves:read", "leaves:approve", "leaves:delete", "leave:manage", "approvals:approve",
    "reports:read", "reports:review", "reports:create",
    "announcements:read", "announcements:create", "announcements:manage",
    "events:read", "events:create", "events:manage",
    "polls:read", "polls:create", "polls:manage",
    "circulars:read", "circulars:create", "circulars:manage",
    "bookings:read", "bookings:create", "bookings:manage",
    "helpdesk:read", "helpdesk:create", "helpdesk:manage",
    "assets:read", "assets:create", "assets:update", "assets:delete",
    "finance:read", "finance:create", "finance:update", "finance:delete", "finance:export", "finance:approve",
    "finance:fees:view", "finance:fees:manage", "finance:fees:collect", "finance:reconciliation:manage", "finance:scholarships:view", "finance:scholarships:approve",
    "finance:tax:view", "finance:tax:manage", "finance:tax:override", "finance:purchases:create", "finance:purchases:approve:tier1", "finance:purchases:approve:tier2", "finance:purchases:approve:final", "finance:payroll:view", "finance:payroll:manage", "finance:payroll:export", "finance:reconciliation:execute", "finance:reconciliation:view",
    "accounts:view", "accounts:create", "accounts:manage",
    "recognition:create",
    "canteen:create", "canteen:delete", "canteen:read", "canteen:manage", "canteen:redeem",
    "checklists:update",
    "notifications:update",
    "vehicles:create", "vehicles:update", "vehicles:delete", "vehicles:read", "vehicles:manage", "fleet:read", "fleet:manage", "fleet:book",
    "visitors:create", "visitors:update", "visitors:read", "visitors:manage", "visitor:read", "visitor:issue", "visitor:verify",
    "system:telemetry", "system:manage", "system:admin",
    "system:security:view", "system:security:manage", "system:threat-intel:view", "system:threat-intel:manage", "system:threat-intel:federate",
    "admin:all", "admin:audit", "remediation:approve", "cache:manage", "database:admin", "lakehouse:manage", "mesh:admin", "agents:manage", "edge:monitor", "features:read", "streaming:access",
    "operations:read", "operations:write", "observability:read", "observability:write",
    "profile:read", "profile:write",
    "org:manage",
    "grievances:read",
    "chat:read", "chat:manage",
    "availability:write",
    "media:read", "media:create", "media:manage", "media:share",
    "nfc:admin", "nfc:assign",
    "webauthn:manage",
    "marketplace:install", "marketplace:uninstall",
    "performance:read", "performance:manage", "performance:evaluate", "performance:self",
    "analytics:predict", "analytics:manage", "analytics:read", "analytics:timeseries", "sync:manage", "sync:device",
    "regional:view", "regional:manage", "warehouse:export", "alerts:push_configure",
    "autonomy:view", "autonomy:manage", "compliance:audit", "compliance:forensics", "compliance:read", "compliance:manage", "compliance:export", "financial:forecast",
    "copilot:view", "copilot:interact", "agent:manage",
    "realtime:stream", "triggers:manage", "predictive:retention", "simulation:budget",
    "federated:policies", "federated:audit", "federated:read", "federated:manage", "federated:train", "federation:manage", "resilience:manage", "voice:copilot",
    "workspaces:read", "workspaces:write",
    "documents:read", "documents:generate", "documents:templates:manage", "documents:telemetry:view", "exports:read", "exports:create", "mobile:sync",
    "system:energy:manage", "system:fleet:manage", "system:biometrics:verify", "system:operations:manage", "system:sustainability:view", "system:operations:view",
    "facility:equipment:view", "facility:equipment:manage", "facility:telemetry:ingest", "facility:alerts:view", "facility:alerts:triage", "facility:workorders:view", "facility:workorders:create", "facility:workorders:assign", "facility:workorders:execute", "facility:inventory:manage", "facility:contractors:manage", "facility:energy:loadshed",
    "twin:facilities:read", "twin:facilities:write", "twin:assets:manage", "twin:iot:ingest", "twin:optimization:manage", "twin:emergency:trigger",
    "eco:assets:manage", "eco:carbon:manage", "eco:carbon:view", "eco:ev:manage", "eco:microgrid:control", "eco:reports:generate", "eco:telemetry:ingest",
    "vision:alerts:view", "vision:alerts:manage", "vision:alpr:manage", "vision:cameras:manage", "vision:guards:dispatch", "vision:incidents:manage", "vision:lockdown:execute", "vision:privacy:audit",
    "neuro:clusters:view", "neuro:clusters:manage", "neuro:gpus:view", "neuro:gpus:manage", "neuro:jobs:view", "neuro:jobs:submit", "neuro:jobs:manage", "neuro:metrics:view", "neuro:nodes:view", "neuro:nodes:manage", "neuro:provenance:view", "neuro:provenance:manage", "neuro:scheduler:view", "neuro:scheduler:manage", "neuro:stream:view", "neuro:arbitrage:view", "neuro:arbitrage:manage", "neuro:billing:view", "neuro:billing:manage",
    "alumni:chapters:view", "alumni:chapters:manage", "alumni:directory:view", "alumni:donations:view", "alumni:donations:manage", "alumni:donations:collect", "alumni:events:view", "alumni:events:manage", "alumni:events:rsvp", "alumni:events:checkin", "alumni:jobs:view", "alumni:jobs:post", "alumni:jobs:apply", "alumni:jobs:manage", "alumni:mentorship:view", "alumni:mentorship:manage", "alumni:profile:view", "alumni:profile:manage",
    "supply:contracts:manage", "supply:invoices:match", "supply:orders:approve", "supply:orders:manage", "supply:orders:view", "supply:receipts:record", "supply:requisitions:create", "supply:requisitions:view", "supply:stream:view", "supply:vendors:manage", "supply:vendors:view",
    "curriculum:advising:chat", "curriculum:audit:execute", "curriculum:catalog:manage", "curriculum:plans:approve", "curriculum:plans:edit", "curriculum:plans:view", "curriculum:retention:intervene", "curriculum:retention:view", "curriculum:transfer:articulate",
    "km:advising:audit", "km:analytics:view", "km:ingest:manage", "km:knowledge:search",
    "engage:campaign:manage", "engage:campaign:view", "engage:chat:interact", "engage:preferences:manage", "engage:template:edit", "engage:workflow:manage",
    "exam:approve_marks", "exam:create", "exam:enter_marks", "exam:publish_results", "exam:read",
    "classes:read", "classes:create", "classes:update", "classes:delete",
    "academic_years:manage", "student_attendance:read", "student_attendance:manage", "timetables:read", "timetables:manage", "enquiries:read", "enquiries:manage", "affiliations:manage",
    "reviews:read", "reviews:create", "reviews:update",
    "agent:workflows:view", "agent:workflows:create", "agent:workflows:execute", "agent:workflows:approve", "agent:workflows:manage",
    "agent:memory:view", "agent:memory:manage", "agent:audit:view", "agent:guardrails:manage", "agent:killswitch:engage", "agent:telemetry:view",
  ],
  principal: [
    "student.create", "students:create", "students:read", "students:update", "students:delete", "students:write",
    "marks.approve", "marks:approve", "exam:approve_marks", "exam:create", "exam:enter_marks", "exam:publish_results", "exam:read",
    "teacher.assign", "teacher:assign", "academic.grade.create", "academic:grade:create",
    "staff:read", "staff:create", "staff:update",
    "attendance:read", "attendance:manage",
    "tasks:read", "tasks:create", "tasks:assign",
    "leaves:read", "leaves:approve", "leaves:delete", "leave:manage", "approvals:approve",
    "reports:read", "reports:review", "reports:create",
    "announcements:read", "announcements:create",
    "events:read", "events:create",
    "polls:read",
    "circulars:read", "circulars:create", "circulars:manage",
    "bookings:read", "bookings:create", "bookings:manage",
    "helpdesk:read", "helpdesk:create", "helpdesk:manage",
    "assets:read", "assets:create", "assets:update",
    "finance:read", "finance:create", "finance:update", "finance:export", "finance:approve",
    "finance:fees:view", "finance:fees:manage", "finance:fees:collect", "finance:reconciliation:manage", "finance:scholarships:view", "finance:scholarships:approve",
    "finance:tax:view", "finance:tax:override", "finance:purchases:create", "finance:purchases:approve:tier1", "finance:purchases:approve:tier2", "finance:purchases:approve:final", "finance:payroll:view", "finance:payroll:manage", "finance:payroll:export", "finance:reconciliation:execute", "finance:reconciliation:view",
    "accounts:view",
    "recognition:create",
    "canteen:create", "canteen:read", "canteen:manage", "canteen:redeem",
    "checklists:update",
    "notifications:update",
    "visitors:create", "visitors:update", "visitors:read", "visitors:manage", "visitor:read", "visitor:issue", "visitor:verify",
    "vehicles:read", "vehicles:manage", "fleet:read", "fleet:manage", "fleet:book",
    "grievances:read",
    "chat:read", "chat:manage",
    "availability:write",
    "media:read", "media:create", "media:share",
    "nfc:admin", "nfc:assign",
    "webauthn:manage",
    "marketplace:install", "marketplace:uninstall",
    "classes:read", "classes:create", "classes:update", "classes:delete",
    "academic_years:manage",
    "student_attendance:read", "student_attendance:manage",
    "timetables:read", "timetables:manage",
    "enquiries:read", "enquiries:manage",
    "affiliations:manage",
    "reviews:read", "reviews:create", "reviews:update",
    "documents:read", "documents:generate", "documents:templates:manage", "documents:telemetry:view", "exports:read", "exports:create", "mobile:sync",
    "biometric:enroll", "biometric:admin",
    "performance:read", "performance:manage", "performance:evaluate", "performance:self",
    "analytics:predict", "analytics:manage", "analytics:read", "analytics:timeseries", "sync:manage", "sync:device",
    "regional:view", "warehouse:export",
    "autonomy:view", "autonomy:manage", "compliance:audit", "compliance:forensics", "compliance:read", "compliance:manage", "compliance:export", "financial:forecast",
    "copilot:view", "copilot:interact", "agent:manage",
    "realtime:stream", "triggers:manage", "predictive:retention", "simulation:budget",
    "federated:policies", "federated:audit", "federated:read", "resilience:manage", "voice:copilot",
    "workspaces:read", "workspaces:write",
    "system:energy:manage", "system:fleet:manage", "system:biometrics:verify", "system:operations:manage", "system:sustainability:view", "system:operations:view",
    "system:security:view", "system:threat-intel:view", "features:read", "operations:read", "observability:read", "profile:read", "profile:write",
    "facility:equipment:view", "facility:equipment:manage", "facility:alerts:view", "facility:alerts:triage", "facility:workorders:view", "facility:workorders:create", "facility:workorders:assign", "facility:inventory:manage", "facility:contractors:manage", "facility:energy:loadshed",
    "twin:facilities:read", "twin:facilities:write", "twin:assets:manage", "twin:optimization:manage",
    "eco:assets:manage", "eco:carbon:manage", "eco:carbon:view", "eco:reports:generate",
    "vision:alerts:view", "vision:alerts:manage", "vision:cameras:manage", "vision:guards:dispatch", "vision:incidents:manage", "vision:lockdown:execute", "vision:privacy:audit",
    "neuro:clusters:view", "neuro:gpus:view", "neuro:jobs:view", "neuro:jobs:submit", "neuro:metrics:view", "neuro:nodes:view", "neuro:provenance:view", "neuro:scheduler:view", "neuro:stream:view", "neuro:billing:view",
    "alumni:chapters:view", "alumni:chapters:manage", "alumni:directory:view", "alumni:donations:view", "alumni:donations:manage", "alumni:events:view", "alumni:events:manage", "alumni:events:rsvp", "alumni:events:checkin", "alumni:jobs:view", "alumni:jobs:post", "alumni:jobs:manage", "alumni:mentorship:view", "alumni:mentorship:manage", "alumni:profile:view", "alumni:profile:manage",
    "supply:contracts:manage", "supply:orders:approve", "supply:orders:view", "supply:receipts:record", "supply:requisitions:create", "supply:requisitions:view", "supply:stream:view", "supply:vendors:view",
    "curriculum:advising:chat", "curriculum:audit:execute", "curriculum:catalog:manage", "curriculum:plans:approve", "curriculum:plans:edit", "curriculum:plans:view", "curriculum:retention:intervene", "curriculum:retention:view", "curriculum:transfer:articulate",
    "km:advising:audit", "km:analytics:view", "km:knowledge:search",
    "engage:campaign:manage", "engage:campaign:view", "engage:chat:interact", "engage:preferences:manage", "engage:template:edit", "engage:workflow:manage",
    "agent:workflows:view", "agent:workflows:execute", "agent:workflows:approve", "agent:memory:view", "agent:audit:view", "agent:telemetry:view",
  ],
  hod: [
    "marks.enter", "marks:enter", "exam:read", "exam:enter_marks",
    "staff:read",
    "attendance:read", "attendance:manage",
    "tasks:read", "tasks:create", "tasks:assign",
    "leaves:read", "leaves:approve", "approvals:approve",
    "reports:read", "reports:review", "reports:create",
    "announcements:read", "announcements:create",
    "events:read", "events:create",
    "polls:read",
    "circulars:read", "circulars:create",
    "bookings:read", "bookings:create",
    "helpdesk:read", "helpdesk:create",
    "assets:read",
    "finance:create", "finance:update", "finance:read", "finance:fees:view", "finance:scholarships:view",
    "finance:tax:view", "finance:purchases:create", "finance:purchases:approve:tier1", "finance:payroll:view",
    "notifications:update",
    "visitors:create", "visitors:read", "visitor:read",
    "grievances:read",
    "chat:read", "chat:manage",
    "availability:write",
    "media:read", "media:create", "media:share",
    "students:read", "classes:read", "student_attendance:read",
    "timetables:read", "timetables:manage",
    "documents:read", "documents:generate", "exports:read", "exports:create", "mobile:sync",
    "enquiries:read",
    "reviews:read", "reviews:create",
    "performance:read", "performance:evaluate", "performance:self",
    "analytics:predict", "analytics:read",
    "regional:view",
    "autonomy:view", "autonomy:manage",
    "copilot:view", "copilot:interact",
    "federated:policies", "voice:copilot",
    "workspaces:read", "workspaces:write",
    "facility:equipment:view", "facility:alerts:view", "facility:workorders:view", "facility:workorders:create",
    "twin:facilities:read", "eco:carbon:view", "eco:reports:generate",
    "vision:alerts:view",
    "neuro:clusters:view", "neuro:jobs:view", "neuro:jobs:submit", "neuro:metrics:view",
    "alumni:directory:view", "alumni:events:view", "alumni:events:rsvp", "alumni:events:checkin", "alumni:jobs:view", "alumni:jobs:post", "alumni:mentorship:view", "alumni:profile:view",
    "supply:requisitions:view", "supply:requisitions:create", "supply:orders:view",
    "curriculum:plans:view", "curriculum:plans:edit", "curriculum:retention:view", "curriculum:advising:chat",
    "km:knowledge:search",
    "engage:chat:interact",
    "operations:read", "profile:read", "profile:write",
    "agent:workflows:view", "agent:workflows:execute", "agent:workflows:approve", "agent:memory:view", "agent:telemetry:view",
  ],
  staff: [
    "marks.enter", "marks:enter", "exam:read", "exam:enter_marks",
    "staff:read",
    "announcements:read",
    "events:read",
    "polls:read",
    "circulars:read",
    "attendance:read",
    "tasks:read",
    "leaves:read", "leaves:delete",
    "reports:create", "reports:read",
    "notifications:update",
    "availability:write",
    "grievances:create", "grievances:read",
    "canteen:read", "canteen:create",
    "bookings:read", "bookings:create",
    "helpdesk:read", "helpdesk:create",
    "assets:read",
    "chat:read", "chat:manage",
    "finance:create", "finance:read", "finance:fees:view",
    "finance:purchases:create", "finance:payroll:view",
    "media:read", "media:create", "media:share",
    "timetables:read",
    "documents:read", "exports:read", "mobile:sync",
    "performance:read", "performance:self",
    "sync:device",
    "webauthn:manage",
    "marketplace:install", "marketplace:uninstall",
    "biometric:enroll",
    "workspaces:read", "workspaces:write",
    "facility:equipment:view", "facility:workorders:view", "facility:workorders:create", "facility:workorders:execute",
    "twin:facilities:read", "eco:carbon:view",
    "vision:alerts:view",
    "neuro:jobs:view", "neuro:jobs:submit",
    "alumni:directory:view", "alumni:events:view", "alumni:events:rsvp", "alumni:jobs:view", "alumni:mentorship:view", "alumni:profile:view", "alumni:profile:manage",
    "supply:requisitions:view", "supply:requisitions:create",
    "curriculum:plans:view", "curriculum:advising:chat",
    "km:knowledge:search",
    "engage:chat:interact",
    "reviews:read", "reviews:create",
    "profile:read", "profile:write",
    "agent:workflows:view", "agent:workflows:execute",
  ],
  accounts: [
    "staff:read",
    "announcements:read",
    "events:read",
    "polls:read",
    "circulars:read",
    "attendance:read",
    "tasks:read",
    "leaves:read",
    "reports:create", "reports:read",
    "notifications:update",
    "availability:write",
    "grievances:create", "grievances:read",
    "canteen:read", "canteen:create",
    "bookings:read", "bookings:create",
    "helpdesk:read", "helpdesk:create",
    "assets:read",
    "chat:read", "chat:manage",
    "finance:read", "finance:create", "finance:update", "finance:delete", "finance:export", "finance:approve",
    "finance:fees:view", "finance:fees:manage", "finance:fees:collect", "finance:reconciliation:manage", "finance:scholarships:view", "finance:scholarships:approve",
    "finance:tax:view", "finance:tax:manage", "finance:tax:override", "finance:purchases:create", "finance:purchases:approve:tier1", "finance:purchases:approve:tier2", "finance:payroll:view", "finance:payroll:manage", "finance:payroll:export", "finance:reconciliation:execute", "finance:reconciliation:view",
    "accounts:view", "accounts:create", "accounts:manage",
    "documents:read", "documents:generate", "exports:read", "exports:create",
    "media:read", "media:create", "media:share",
    "workspaces:read", "workspaces:write",
    "supply:invoices:match", "supply:receipts:record", "supply:orders:view", "supply:vendors:view",
    "alumni:donations:view", "alumni:donations:collect", "alumni:donations:manage",
    "neuro:billing:view", "neuro:billing:manage",
    "profile:read", "profile:write",
    "agent:workflows:view", "agent:workflows:approve",
  ],
  purchase: [
    "staff:read",
    "announcements:read",
    "events:read",
    "polls:read",
    "circulars:read",
    "attendance:read",
    "tasks:read",
    "leaves:read",
    "reports:create", "reports:read",
    "notifications:update",
    "availability:write",
    "grievances:create", "grievances:read",
    "canteen:read", "canteen:create",
    "bookings:read", "bookings:create",
    "helpdesk:read", "helpdesk:create",
    "assets:read", "assets:create", "assets:update", "assets:delete",
    "chat:read", "chat:manage",
    "finance:create", "finance:update", "finance:read", "finance:fees:view",
    "finance:tax:view", "finance:purchases:create", "finance:purchases:approve:tier1", "finance:purchases:approve:tier2",
    "media:read", "media:create", "media:share",
    "documents:read", "exports:read",
    "workspaces:read", "workspaces:write",
    "supply:contracts:manage", "supply:invoices:match", "supply:orders:approve", "supply:orders:manage", "supply:orders:view", "supply:receipts:record", "supply:requisitions:create", "supply:requisitions:view", "supply:stream:view", "supply:vendors:manage", "supply:vendors:view",
    "profile:read", "profile:write",
    "agent:workflows:view", "agent:workflows:approve",
  ],
};

export const VALID_STAFF_ROLES: StaffRole[] = [
  "super_admin",
  "admin",
  "principal",
  "hod",
  "staff",
  "accounts",
  "purchase",
  "regional_admin",
  "regional_auditor",
  "coordinator",
  "institutional_head",
  "academic_coordinator",
  "exam_coordinator",
  "teacher",
  "inspector",
  "system",
];

const DOT_TO_COLON_MAP: Record<string, string> = {
  "student.create": "students:create",
  "marks.enter": "exam:enter_marks",
  "marks.approve": "exam:approve_marks",
  "academic.grade.create": "classes:create",
  "teacher.assign": "timetables:manage",
  "campus.approve": "affiliations:manage",
};

export function isValidRole(role: string): role is StaffRole {
  return VALID_STAFF_ROLES.includes(role as StaffRole);
}

export function hasPermission(role: string, permission: Permission) {
  if (!isValidRole(role)) {
    console.warn(`[Security Alert] Invalid role attempted in RBAC check: "${role}"`);
    return false;
  }
  if (role === "super_admin") return true;

  const perms = rolePermissions[role] ?? [];
  if (perms.includes(permission)) return true;

  // Check alias mappings (dot-notation <-> colon-notation)
  if (DOT_TO_COLON_MAP[permission] && perms.includes(DOT_TO_COLON_MAP[permission])) {
    return true;
  }

  // Check reverse mapping
  for (const [dot, colon] of Object.entries(DOT_TO_COLON_MAP)) {
    if (colon === permission && perms.includes(dot)) {
      return true;
    }
  }

  return false;
}

export function getRolePermissions(role: string) {
  if (!isValidRole(role)) {
    return [];
  }
  return rolePermissions[role] ?? [];
}
