// Flutter App Configuration Constants
// Auto-generated by Sprint-005 implementation

import 'dart:io';
import 'package:flutter/foundation.dart';

/// Centralized app configuration for ThaibaHive Mobile Companion App
/// Version: 1.7.0
class AppConfig {
  /// Private constructor to prevent instantiation
  AppConfig._();

  /// Base API URL - determined by environment
  static String get apiBaseUrl {
    final envUrl = String.fromEnvironment('API_BASE_URL');
    if (envUrl.isNotEmpty) return envUrl;

    if (kDebugMode) {
      if (!kIsWeb && Platform.isAndroid) {
        return 'http://10.0.2.2:3000/api';
      }
      return 'http://localhost:3000/api';
    }

    return 'https://thaiba-hive.vercel.app/api';
  }

  /// Web app base URL for non-native platforms
  static String get webBaseUrl {
    final envUrl = String.fromEnvironment('WEB_BASE_URL');
    if (envUrl.isNotEmpty) return envUrl;

    if (kDebugMode) {
      if (!kIsWeb && Platform.isAndroid) {
        return 'http://10.0.2.2:3000';
      }
      return 'http://localhost:3000';
    }

    return 'https://thaiba-hive.vercel.app';
  }

  /// Firebase Cloud Messaging configuration
  static const String firebaseAndroidChannelId = 'thaibahive_mobile';
  static const String firebaseIOSCategory = 'thaibahive_mobile';

  /// Push notification channels
  static const String defaultNotificationChannelId = 'general';
  static const String defaultNotificationChannelName = 'General Notifications';
  static const String defaultNotificationChannelDescription = 'App notifications';

  /// Mobile synchronization settings
  static const Duration syncTimeout = Duration(seconds: 30);
  static const int maxOfflineQueueSize = 1000;
  static const Duration offlineSyncRetryDelay = Duration(seconds: 5);
  static const Duration maxOfflineSyncRetryAttempts = 3;

  /// QR code scanner settings
  static const int qrCodeScanTimeoutSeconds = 10;
  static const double qrCodeMinSize = 100.0;
  static const double qrCodeMaxSize = 300.0;

  /// Location tracking settings
  static const double locationAccuracy = 10.0; // meters
  static const Duration locationUpdateInterval = Duration(seconds: 60);
  static const double locationMinDistance = 10.0; // meters

  /// Offline storage encryption
  static const String offlineStorageEncryptionKey = 'thaibahive_mobile_secret_key';
  static const String offlineStorageSalt = 'thaibahive_mobile_salt';

  /// API request settings
  static const Duration apiRequestTimeout = Duration(seconds: 30);
  static const int apiRequestRetryCount = 3;
  static const List<String> apiRequestHeaders = [
    'application/json',
    'auth_token',
    'device_id',
  ];

  /// UI/UX settings
  static const double defaultBorderRadius = 8.0;
  static const double cardElevation = 2.0;
  static const Duration animationDuration = Duration(milliseconds: 200);

  /// Feature flags
  static const bool enableOfflineMode = true;
  static const bool enablePushNotifications = true;
  static const bool enableLocationTracking = false; // Disabled by default for privacy
  static const bool enableBackgroundSync = true;
}
