import { WorkflowDsl } from "../dsl/schema";

export const institutionalWorkflowTemplates: WorkflowDsl[] = [
  {
    key: "academic-attendance-remediation",
    name: "Autonomous Attendance Anomaly Remediation",
    description: "Detects attendance deficits, cross-checks biometric logs, and reconciles section attendance registers.",
    dslVersion: 1,
    version: 1,
    triggers: [{ type: "schedule", cron: "0 17 * * 1-5" }],
    defaults: { concurrencyPolicy: "skip", maxRetries: 2, timeoutMs: 300000, onFailure: "compensate" },
    steps: [
      {
        key: "detect-anomalies",
        type: "action",
        agent: "academic-agent",
        tool: "academic.attendance.get_anomalies",
        input: { thresholdPercent: 75 },
      },
      {
        key: "reconcile-attendance",
        type: "action",
        agent: "academic-agent",
        tool: "academic.attendance.reconcile",
        input: { sectionId: "sec_101", date: "{{trigger.date}}" },
      },
    ],
  },
  {
    key: "academic-grade-publication",
    name: "End-of-Term Grade Verification & Publication",
    description: "Batches course assessments, verifies grade curves, and triggers human approval before publishing to SIS.",
    dslVersion: 1,
    version: 1,
    triggers: [{ type: "manual" }],
    defaults: { concurrencyPolicy: "allow", maxRetries: 2, timeoutMs: 600000, onFailure: "compensate" },
    steps: [
      {
        key: "post-grades",
        type: "action",
        agent: "academic-agent",
        tool: "academic.grades.post_batch",
        input: { termId: "fall_2026", courseId: "CS101" },
        approval: { required: true, permission: "agent:workflows:approve", severity: "high", onExpiry: "escalate" },
      },
    ],
  },
  {
    key: "academic-timetable-conflict-resolution",
    name: "Departmental Timetable Conflict Resolution",
    description: "Scans classroom allocations, identifies room double-bookings, and synthesizes collision-free schedules.",
    dslVersion: 1,
    version: 1,
    triggers: [{ type: "event", topic: "schedule.updated" }],
    defaults: { concurrencyPolicy: "skip", maxRetries: 2, timeoutMs: 300000, onFailure: "compensate" },
    steps: [
      {
        key: "resolve-conflicts",
        type: "action",
        agent: "academic-agent",
        tool: "academic.timetables.resolve_conflicts",
        input: { departmentId: "dept_cs", academicYear: "2026-2027" },
      },
    ],
  },
  {
    key: "finance-tuition-reconciliation",
    name: "3-Way Payment Gateway & Ledger Reconciliation",
    description: "Reconciles Razorpay/Stripe transactions against student fee accounts and ERP general ledgers.",
    dslVersion: 1,
    version: 1,
    triggers: [{ type: "schedule", cron: "0 2 * * *" }],
    defaults: { concurrencyPolicy: "skip", maxRetries: 3, timeoutMs: 900000, onFailure: "compensate" },
    steps: [
      {
        key: "reconcile-fees",
        type: "action",
        agent: "finance-agent",
        tool: "finance.fees.reconcile",
        input: { termId: "fall_2026" },
      },
    ],
  },
  {
    key: "finance-fee-waiver-triage",
    name: "Scholarship & Financial Aid Waiver Triage",
    description: "Validates hardship documentation, checks institutional budget caps, and requests Principal approval.",
    dslVersion: 1,
    version: 1,
    triggers: [{ type: "manual" }],
    defaults: { concurrencyPolicy: "allow", maxRetries: 1, timeoutMs: 300000, onFailure: "compensate" },
    steps: [
      {
        key: "apply-waiver",
        type: "action",
        agent: "finance-agent",
        tool: "finance.fees.waive",
        input: { studentId: "std_404", amount: 15000, reason: "Merit scholarship" },
        approval: { required: true, permission: "finance:scholarships:approve", severity: "high", onExpiry: "hold" },
      },
    ],
  },
  {
    key: "security-lockdown-escalation",
    name: "Campus Threat Lockdown Escalation",
    description: "Triages perimeter breach alerts from Vision Shield and executes physical lockdown with guard dispatch.",
    dslVersion: 1,
    version: 1,
    triggers: [{ type: "anomaly", subsystem: "vision", severityThreshold: "critical" }],
    defaults: { concurrencyPolicy: "allow", maxRetries: 1, timeoutMs: 120000, onFailure: "compensate" },
    steps: [
      {
        key: "lockdown-zone",
        type: "action",
        agent: "security-agent",
        tool: "security.lockdown.escalate",
        input: { zoneId: "zone_north_gate", reason: "Unauthorized intrusion", lockdownType: "building_specific" },
        approval: { required: true, permission: "vision:lockdown:execute", severity: "critical", onExpiry: "escalate" },
      },
    ],
  },
  {
    key: "facilities-energy-loadshed",
    name: "Automated Campus Energy Load-Shedding & HVAC Setbacks",
    description: "Monitors peak power demand, detects idle lecture halls, and applies setback temperature setpoints.",
    dslVersion: 1,
    version: 1,
    triggers: [{ type: "schedule", cron: "0 18 * * 1-5" }],
    defaults: { concurrencyPolicy: "skip", maxRetries: 2, timeoutMs: 300000, onFailure: "compensate" },
    steps: [
      {
        key: "read-telemetry",
        type: "action",
        agent: "facilities-agent",
        tool: "facilities.energy.get_telemetry",
        input: { buildingId: "bld_engineering" },
      },
      {
        key: "optimize-hvac",
        type: "action",
        agent: "facilities-agent",
        tool: "facilities.hvac.optimize_schedule",
        input: { zoneId: "Auditorium_B", targetSetpointC: 26.5, setbackMode: true },
      },
    ],
  },
  {
    key: "facilities-work-order-dispatch",
    name: "Predictive Maintenance Work Order Dispatch",
    description: "Detects equipment telemetry anomalies and generates prioritized maintenance work orders.",
    dslVersion: 1,
    version: 1,
    triggers: [{ type: "event", topic: "telemetry.anomaly" }],
    defaults: { concurrencyPolicy: "allow", maxRetries: 2, timeoutMs: 180000, onFailure: "compensate" },
    steps: [
      {
        key: "dispatch-order",
        type: "action",
        agent: "facilities-agent",
        tool: "facilities.work_orders.create",
        input: { location: "Science_Block_Wing_3", issueCategory: "electrical", priority: "high", description: "Power fluctuation detected" },
      },
    ],
  },
  {
    key: "hr-faculty-onboarding",
    name: "Faculty Digital Identity & Badge Provisioning",
    description: "Provisions digital credentials, sets up institutional email, and issues smart RFID badges for new hires.",
    dslVersion: 1,
    version: 1,
    triggers: [{ type: "manual" }],
    defaults: { concurrencyPolicy: "allow", maxRetries: 2, timeoutMs: 300000, onFailure: "compensate" },
    steps: [
      {
        key: "provision-creds",
        type: "action",
        agent: "hr-agent",
        tool: "hr.onboarding.provision_credentials",
        input: { staffId: "staff_108", officialEmail: "dr.sarah@thaiba.edu", assignedDepartment: "Computer Science", badgeNumber: "BADGE-CS-108" },
      },
    ],
  },
  {
    key: "hr-leave-balance-adjustment",
    name: "Faculty Sabbatical & Leave Adjustment",
    description: "Computes accrued leave days, evaluates tenure policy, and pauses for HOD/Principal sign-off.",
    dslVersion: 1,
    version: 1,
    triggers: [{ type: "manual" }],
    defaults: { concurrencyPolicy: "allow", maxRetries: 1, timeoutMs: 300000, onFailure: "compensate" },
    steps: [
      {
        key: "calculate-balance",
        type: "action",
        agent: "hr-agent",
        tool: "hr.leave.calculate_balance",
        input: { staffId: "staff_202", leaveType: "sabbatical" },
      },
      {
        key: "post-leave-approval",
        type: "action",
        agent: "hr-agent",
        tool: "hr.leave.post_approval",
        input: { requestId: "lvr_99", staffId: "staff_202", days: 10, approved: true },
        approval: { required: true, permission: "leaves:approve", severity: "high", onExpiry: "hold" },
      },
    ],
  },
];
